#!/usr/bin/env bash


# exit if any command returns a non-zero status
set -e


OUTPUT_DIR="/tmp/s3-bash-scripts"

if [ -d "$OUTPUT_DIR" ]; then
  rm -r $OUTPUT_DIR
fi

mkdir -p $OUTPUT_DIR


NUM_FILES=$((RANDOM % 6 + 5))


for i in $(seq 1 $NUM_FILES); do
  echo "This is file $i" > $OUTPUT_DIR/file$i.txt
  echo "Uploading file$i.txt"

done


echo "uploading files to s3"


for file in $OUTPUT_DIR/*; do
  aws s3 cp $file s3://$1/
done